//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class WCSocialInfluenceInfo;

@interface WCObjectOperation : NSObject <NSCoding>
{
    int snsOperateFlag;
    WCSocialInfluenceInfo *socialInfluenceInfo;
}

@property(retain, nonatomic) WCSocialInfluenceInfo *socialInfluenceInfo; // @synthesize socialInfluenceInfo;
@property(nonatomic) int snsOperateFlag; // @synthesize snsOperateFlag;

- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

